import PDFDocument from 'pdfkit';

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { customer, shop, components, buildData, timestamp } = req.body;
    const doc = new PDFDocument({ margin: 50 });
    let buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      const pdfBuffer = Buffer.concat(buffers);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="build-sheet-${customer.name || 'customer'}.pdf"`);
      res.send(pdfBuffer);
    });

    // ---- HEADER ----
    doc.rect(0, 0, 612, 80).fill('#2563eb');
    // Uncomment if logo is available:
    // doc.image('public/logo.png', 480, 15, { width: 100 });
    doc.font('Helvetica-Bold').fontSize(22).fillColor('white').text('CrankSmith Pro Build Sheet', 50, 30);
    doc.moveDown(2).fillColor('#111111');
    doc.fontSize(10).font('Helvetica-Oblique').fillColor('#111').text(`Generated: ${new Date(timestamp).toLocaleString()}`, 50, 90);

    // ---- SHOP & CUSTOMER INFO ----
    doc.font('Helvetica-Bold').fontSize(13).fillColor('#2563eb').text('SHOP INFORMATION:');
    doc.moveDown(0.2).strokeColor('#e5e7eb').lineWidth(1.5).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.font('Helvetica').fontSize(10).fillColor('#111').text(`${shop.name}\n${shop.address}\n${shop.phone} • ${shop.email}`, { indent: 8 });
    doc.moveDown(0.7).font('Helvetica-Bold').fontSize(13).fillColor('#2563eb').text('CUSTOMER INFORMATION:');
    doc.moveDown(0.2).strokeColor('#e5e7eb').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.font('Helvetica').fontSize(10).fillColor('#111').text(`Name: ${customer.name}\nEmail: ${customer.email}\nPhone: ${customer.phone}\nBike: ${customer.bikeModel}`, { indent: 8 });

    // ---- COMPONENT SPEC ----
    doc.moveDown(0.7).font('Helvetica-Bold').fontSize(13).fillColor('#2563eb').text('COMPONENT SPECIFICATION:');
    doc.moveDown(0.2).strokeColor('#e5e7eb').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.font('Helvetica').fontSize(10).fillColor('#111').text(
      `Crankset: ${components.crankset.model} ${components.crankset.variant}\nCassette: ${components.cassette.model} ${components.cassette.variant}\nDerailleur: ${components.derailleur.model} ${components.derailleur.variant}`,
      { indent: 8 }
    );

    // ---- BUILD SUMMARY ----
    doc.moveDown(0.7).font('Helvetica-Bold').fontSize(13).fillColor('#2563eb').text('BUILD SUMMARY:');
    doc.moveDown(0.2).strokeColor('#e5e7eb').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.font('Helvetica').fontSize(10).fillColor('#111').text(
      `Total Weight: ${buildData.totalWeight}g\nGear Range: ${buildData.gearRange}\nChain Length: ${buildData.chainLength} links\nLabor Estimate: ${buildData.laborTime}`,
      { indent: 8 }
    );

    // ---- PARTS LIST TABLE ----
    drawPartsTable(doc, buildData.partsList);

    // ---- INSTALLATION STEPS ----
    doc.addPage();
    doc.font('Helvetica-Bold').fontSize(13).fillColor('#2563eb').text('INSTALLATION STEPS:');
    doc.moveDown(0.2).strokeColor('#e5e7eb').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.font('Helvetica').fontSize(10).fillColor('#111');
    buildData.installationSteps.forEach((step, i) => {
      doc.font('Helvetica-Bold').text(`${i + 1}. ${step.title}`);
      doc.font('Helvetica').text(`   ${step.description}`);
      if (step.torque) doc.fillColor('#f59e0b').text(`   Torque: ${step.torque}`);
      if (step.specialTools) doc.fillColor('#2563eb').text(`   Tools: ${step.specialTools}`);
      doc.moveDown(0.6).fillColor('#111');
    });

    // ---- WARNINGS ----
    if (buildData.warnings.length > 0) {
      doc.moveDown().font('Helvetica-Bold').fontSize(13).fillColor('#ef4444').text('WARNINGS:');
      doc.font('Helvetica').fontSize(10).fillColor('#ef4444');
      buildData.warnings.forEach(w => doc.text(`• ${w}`));
      doc.fillColor('#111');
    }

    // ---- MINI BAR CHART: GEAR USAGE ----
    if (buildData.gearUsage?.length) {
      doc.addPage();
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#2563eb').text('GEAR USAGE CHART:');
      doc.moveDown(0.2).strokeColor('#e5e7eb').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
      let chartY = doc.y + 10;
      buildData.gearUsage.forEach((gear, i) => {
        doc.font('Helvetica').fontSize(10).fillColor('#111').text(gear.label, 60, chartY);
        doc.rect(130, chartY, gear.usage * 2, 10).fill('#2563eb');
        doc.fillColor('#111').text(`${gear.usage}%`, 340, chartY);
        chartY += 18;
      });
      doc.fillColor('#111');
    }

    doc.moveDown(2).font('Helvetica-Oblique').fontSize(10).fillColor('#111').text('Generated by CrankSmith Pro – Professional Drivetrain Analysis', 50);
    doc.end();

  } catch (error) {
    console.error('PDF generation error:', error);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
}

// Ultimate Pro Table Helper: fixed row height, ellipsis, alternate row shading
function drawPartsTable(doc, partsList, startY = null) {
  const left = 60;
  let y = startY || doc.y;
  const colWidths = [100, 60, 30, 50, 170]; // Name, Part #, Qty, Weight, Notes
  const rowHeight = 18;
  const headerBg = '#e5e7eb';
  const altRowBg = '#f1f5f9'; // alternate row light blue

  // Header row background
  doc.rect(left, y, colWidths.reduce((a, b) => a + b), rowHeight).fill(headerBg);
  doc.font('Helvetica-Bold').fontSize(11).fillColor('#2563eb');
  doc.text('Name', left + 4, y + 3, { width: colWidths[0] - 8 });
  doc.text('Part #', left + colWidths[0] + 4, y + 3, { width: colWidths[1] - 8 });
  doc.text('Qty', left + colWidths[0] + colWidths[1] + 4, y + 3, { width: colWidths[2] - 8 });
  doc.text('Weight', left + colWidths[0] + colWidths[1] + colWidths[2] + 4, y + 3, { width: colWidths[3] - 8 });
  doc.text('Notes', left + colWidths[0] + colWidths[1] + colWidths[2] + colWidths[3] + 4, y + 3, { width: colWidths[4] - 8 });

  // Header row bottom border
  doc.strokeColor('#cbd5e1').moveTo(left, y + rowHeight).lineTo(left + colWidths.reduce((a, b) => a + b), y + rowHeight).stroke();

  y += rowHeight;

  // Table rows
  doc.font('Helvetica').fontSize(10).fillColor('#111');
  partsList.forEach((p, i) => {
    // Alternate row shading
    if (i % 2 === 1) {
      doc.rect(left, y, colWidths.reduce((a, b) => a + b), rowHeight).fill(altRowBg);
    }
    // Columns: fixed width, ellipsis, no wrapping
    doc.fillColor('#111');
    doc.text(p.name, left + 4, y + 3, { width: colWidths[0] - 8, ellipsis: true });
    doc.text(p.partNumber, left + colWidths[0] + 4, y + 3, { width: colWidths[1] - 8, ellipsis: true });
    doc.text(p.quantity, left + colWidths[0] + colWidths[1] + 4, y + 3, { width: colWidths[2] - 8, ellipsis: true });
    doc.text(p.weight, left + colWidths[0] + colWidths[1] + colWidths[2] + 4, y + 3, { width: colWidths[3] - 8, ellipsis: true });
    doc.text(p.notes, left + colWidths[0] + colWidths[1] + colWidths[2] + colWidths[3] + 4, y + 3, { width: colWidths[4] - 8, ellipsis: true });

    // Optional: vertical grid lines (remove if you want a cleaner look)
    /*
    for (let k = 1; k < colWidths.length; k++) {
      const x = left + colWidths.slice(0, k).reduce((a, b) => a + b, 0);
      doc.strokeColor('#cbd5e1').moveTo(x, y).lineTo(x, y + rowHeight).stroke();
    }
    */

    y += rowHeight;
    // Page break if near bottom
    if (y > 720) {
      doc.addPage();
      y = 50;
      // Redraw table header on new page
      doc.rect(left, y, colWidths.reduce((a, b) => a + b), rowHeight).fill(headerBg);
      doc.font('Helvetica-Bold').fontSize(11).fillColor('#2563eb');
      doc.text('Name', left + 4, y + 3, { width: colWidths[0] - 8 });
      doc.text('Part #', left + colWidths[0] + 4, y + 3, { width: colWidths[1] - 8 });
      doc.text('Qty', left + colWidths[0] + colWidths[1] + 4, y + 3, { width: colWidths[2] - 8 });
      doc.text('Weight', left + colWidths[0] + colWidths[1] + colWidths[2] + 4, y + 3, { width: colWidths[3] - 8 });
      doc.text('Notes', left + colWidths[0] + colWidths[1] + colWidths[2] + colWidths[3] + 4, y + 3, { width: colWidths[4] - 8 });
      doc.strokeColor('#cbd5e1').moveTo(left, y + rowHeight).lineTo(left + colWidths.reduce((a, b) => a + b), y + rowHeight).stroke();
      y += rowHeight;
    }
  });
  doc.moveDown(1);
}
